version: '3'

services:
  splunk:
    hostname: splunk
    image: splunk/splunk:7.0.3
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_CMD: 'edit user admin -password admin -role admin -auth admin:changeme'
      SPLUNK_ENABLE_LISTEN: 9997
    ports:
      - "8000:8000" # splunk UI
    volumes:
      - "./splunk-apps/demo_hf:/opt/splunk/etc/apps/demo_hf"
      - "./splunk-apps/demo_idx:/opt/splunk/etc/apps/demo_idx"
      - "./splunk-apps/demo_shc:/opt/splunk/etc/apps/demo_shc"

  splunkforwarder:
    hostname: splunkforwarder
    image: splunk/universalforwarder:7.0.3
    links:
      - "splunk"
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_CMD: 'edit user admin -password admin -role admin -auth admin:changeme'
      SPLUNK_FORWARD_SERVER: 'splunk:9997'
    ports:
      - "8088:8088" # splunk HEC
    volumes:
      - "./splunk-apps/demo_uf:/opt/splunk/etc/apps/demo_uf"
      - "splunklogs:/opt/splunk/var/log"

  fluentbit:
    hostname: fluentbit
    image: fluent/fluent-bit:0.13.2
    links:
      - "splunkforwarder"
    volumes:
      - "./volumes/fluent-bit-etc:/fluent-bit/etc"

  mtail:
    hostname: mtail
    image: mtail-latest:latest
    volumes:
      - "splunklogs:/logs"
      - "./volumes/mtail-progs:/progs"
    entrypoint:
      - "/usr/bin/mtail"
      - "--logs=/logs/splunk/splunkd.log"
      - "--progs=/progs"

volumes:
  splunklogs:
