version: '3'

services:
  splunk:
    hostname: splunk
    image: splunk/splunk:7.0.3
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_CMD: 'edit user admin -password admin -role admin -auth admin:changeme'
      SPLUNK_ENABLE_LISTEN: 9997
    ports:
      - "8000:8000" # splunk UI
    volumes:
      - "./volumes/splunk-apps/demo_hf:/opt/splunk/etc/apps/demo_hf"
      - "./volumes/splunk-apps/demo_idx:/opt/splunk/etc/apps/demo_idx"
      - "./volumes/splunk-apps/demo_shc:/opt/splunk/etc/apps/demo_shc"

  splunkforwarder01:
    hostname: splunkforwarder01
    image: splunk/universalforwarder:7.0.3
    links:
      - "splunk"
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_CMD: 'edit user admin -password admin -role admin -auth admin:changeme'
      SPLUNK_FORWARD_SERVER: 'splunk:9997'
    volumes:
      - "./volumes/splunk-apps/demo_uf:/opt/splunk/etc/apps/demo_uf"
      - "splunk01logs:/opt/splunk/var/log"

  mtail01:
    hostname: mtail01
    image: jaymedh/docker-mtail:latest
    volumes:
      - "splunk01logs:/logs"
      - "./volumes/mtail-progs:/progs"
    entrypoint:
      - "/bin/mtail"
      - "--logs=/logs/splunk/splunkd.log"
      - "--logs=/logs/splunk/metrics.log"
      - "--logs=/logs/introspection/http_event_collector_metrics.log"
      - "--progs=/progs"
    ports:
     - 3903:3903

  splunkforwarder02:
    hostname: splunkforwarder02
    image: splunk/universalforwarder:7.0.3
    links:
      - "splunk"
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_CMD: 'edit user admin -password admin -role admin -auth admin:changeme'
      SPLUNK_FORWARD_SERVER: 'splunk:9997'
    volumes:
      - "./volumes/splunk-apps/demo_uf:/opt/splunk/etc/apps/demo_uf"
      - "splunk02logs:/opt/splunk/var/log"

  mtail02:
    hostname: mtail02
    image: jaymedh/docker-mtail:latest
    volumes:
      - "splunk02logs:/logs"
      - "./volumes/mtail-progs:/progs"
    entrypoint:
      - "/bin/mtail"
      - "--logs=/logs/splunk/splunkd.log"
      - "--logs=/logs/splunk/metrics.log"
      - "--logs=/logs/introspection/http_event_collector_metrics.log"
      - "--progs=/progs"
    ports:
     - 3904:3903

  envoy:
    hostname: envoy
    image: envoyproxy/envoy-alpine:v1.8.0
    links:
      - "splunkforwarder01"
      - "splunkforwarder02"
    volumes:
      - "./volumes/envoy/front-envoy.yaml:/etc/front-envoy.yaml"
    entrypoint:
      - "/usr/local/bin/envoy"
      - "-c"
      - "/etc/front-envoy.yaml"
    ports:
     - 8001:8001

  fluentbit:
    hostname: fluentbit
    image: fluent/fluent-bit:0.14.4
    links:
      - "envoy"
    volumes:
      - "./volumes/fluent-bit-etc:/fluent-bit/etc"

  prometheus:
    hostname: prometheus
    image: prom/prometheus:v2.4.2
    volumes:
     - ./volumes/prometheus-server/prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
     - 9090:9090
    links:
      - "envoy"
      - "fluentbit"
      - "mtail01"
      - "mtail02"

  grafana:
    hostname: grafana
    image: grafana/grafana:5.2.4
    volumes:
     - ./volumes/grafana-config/config.ini:/etc/grafana/config.ini
     - ./volumes/grafana-provisioning:/etc/grafana/provisioning
     - ./volumes/grafana-dashboards:/var/lib/grafana/dashboards
    ports:
     - 3000:3000
    links:
      - "prometheus"

volumes:
  splunk01logs:
  splunk02logs:

