global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'fluentbit'
    scrape_interval: 5s
    metrics_path: /api/v1/metrics/prometheus
    static_configs:
      - targets: ['fluentbit:2020']

  - job_name: 'nginxexporter'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['nginxexporter:9113']

